1. Abel J, Madden M. Drawing words & writing pictures: making comics: manga, graphic novels, and beyond. 1st ed. New York: First Second; 2008. 282 p. 
* Building Blocks
** Drawing Time
*** Action Within a Drawing
    Draw the following (no borders, just one panel each).

    1. A person running
    2. A car speeding
    3. A ball falling
    4. A person stagerring
    5. A newspaper page blowing in the wind

**** Afterwards
     - Which drawings are the most successful at depicting movement?
     - Which aren't working? Why?
     - Make a list of the ways that people use to depict motion.
*** Action Within a Panel
    Draw boxes on three separate sheets of paper, each one about 4" x 6" then draw the following scenarios (each within a single frame).
    - Scenario One:
      + A ball crashes through a window into a kitchen and rips through the newspaper of a person sitting in the room.
      + The person reacts to the window breaking.
      + Optional: a dog catches the ball in midair after it comes through the newspaper.
    - Scenario Two:
      + Person 1 trips Person 2.
      + Person 1 is laughing, person 2 is tryng to catch him or herself and is knocking over a lamp.
    - Scenario Three:
      + Two guys are fighting.
      + Guy 1 throws a rock at guy 2.
      + Guy 2 is hit by the rock, which makes him accidentally shoot his gun into the air.
      + The bullet hits and breaks a chain holding up a heavy lamp over Guy 1's head.
**** Afterwards
     For each panel answer the following questions.
     - Does the panel read consistently? In other words, does the reader's eye easily follow the sequence of events in the order you intended?
     - What are alternate ways of arranging the elements?
     - Does effect clearly follow cause?
     - Do actions themselves follow the left-to-right reading order?
     - If movement is generally against the reading order, is it forceful enough to make the reader follow it? Other things to look at:
       + body language
       + facial expressions
       + motion lines
       + emmanata
     - For Scenario Three, look for compositional solutions that cause the reader's eye to follow the action in a clear trajectory.
** Homework: Drawing in action
   This is essentially the same exercise as the previous one, except more open-ended. It should be wordless.
   
   1. Draw a 5" x 7" border
   2. Create a drawing with the following elements:
      - two characters
      - one or more objects (props)
      - an action and its result
      - The reaction of one or more characters shown in facial expressions or body language
** Extra Credit: Directed jam comic
* Every Picture Tells a Story
* The Strip Club
* Bridging the Gap
* Penciling
* Getting On the Same Page
* Lettering
* Inking the Deal
* Structuring the Story
* Getting Into Character
* Setting the Stage
* Constructing a World
* Black Gold
* Comics In the Age of Mechanical Reproduction
* 24-Hour Comic
* Appendices
** Supplies
** Homework critiques
** Story Cards
** Comic book mini report
** Making Minicomics
