* Outline
** Foreword
** Preface
** One - Opening: Letting the Writer In Us Out
*** Two Modes of Knowing: Sign and Design
- Dorothea Brande: Critic and Artist
- Sign is the Left-Brain Interpreter, the Editor, the Critic - it works to create order and interprets things as literally as possible
- Design is the Right-Brain Clown, the Artist - it creates by finding patterns in the chaotic stream of the current moment and making associations
- Rule-based writing is based on having an outsider impose constraints that you have to meet (e.g. the five-paragraph essay)
- Natural Writing is based on pulling out what you have within
*** The Three Partners:
- The Design Mind should be let free to express whatever is in the stream at the moment
- The Voice: Reading the writing aloud is the bridge between the two - it makes physical the imagined words on the page.
- The Sign Mind steps in aftewards to organize and make sense of things
** Two - Clustering: The Doorway To Your Design Mind
- Her idea of "clustering" is different - more like what others call "mapping"
- Start with a "Nucleus," a central word
- Free-associate outwards from the nucleus
- Keep the time spent short (1 to 5 minutes) and make lots of cluster-writing pairs instead of one monolithic one.
*** The Process of Writing Vignettes
1. Write the nucleus word in the center of the page
2. Free-associate whatever comes to mind, writing it around the nucleus: this is free-writing but without whole sentences so you don't get caught up in trying to edit and make sense of what's coming out
3. If you seem to be stuck, doodle until something comes up again (she suggests extending the map with empty bubbles and arrows to fill in when you have something)
4. Keep going until you have the urge to write
5. Write: You can ignore the map or scan it quickly, limit it to five or ten minutes
6. Finish by referring to whatever impelled you to start writing
7. Read it out loud, making changes until it seems like everything that's there belongs there.
*** Modeling
1. Start with a piece of writing you want to learn from
2. Read the piece
3. Cluster around something that the piece made you think of
4. Write a vignette
** Three - The Receptive "I": The Childhood Origins Of Natural Writing
** Four - The Self-Reflective Mind: Words and the Brain
*** Directing Your Hand: Sign vs Design
- Take a nucleus (the exercise started with a proverb)
- Write about it from the editor's point of view - take everything literally
- Write from the Clown's point of view - map free-form associations and improvise a vignette
** Five - Discovering Design: The Trial-Web Shift
- The Trial-Web Shift: When you cluster/map you free-associate random-ish words that relate to something in the map but not necessarily to each other. The "Trial-Web Shift" is a point where your mind sees a pattern and you know what the cluster is telling you to write about
- Clustering is the yes-and search through the base reality. The shift is a recognition of the game.
- Nucleus -> Cluster -> pattern awareness -> recognition of the pattern -> impulse to write
** Six - The Zen of Improvising: Re-Creations
- Rather than just starting with a blank page, listen to someone else's work and make a cluster, leaving the nucleus blank until later when you can look at the cluster and find the nucleus as the dominant impression
- This is analgous to studying someone else's work of art then re-creating it from memory. The imperfect copy along with improvisation creates something related but new.
** Seven - Recurrences: The Unifying Thread
- Rather than writing a continuous chain where each next thing relates to the current one, using repetition can create a satisfying pattern to latch on to
*** Recurrences
- Sound (alliteration)
- Word segments
- Throw-away words (words that don't seem to suggest much at first, e.g. not nouns or adjectives)
- Concepts
** Eight - Language Rhythms: The Music In Words
** Nine - Images: Inner Eye Directing Writing Hand
** Ten - Wedding Word to Image: Metaphor
- Metaphors are concrete things that our senses can perceive that we use to represent abstract ideas that have no representation.
- They can also work in an opposite direction, taking something concrete, throwing away what it's "meant to do" (or be) and using its appearance only to find what it is (like a bicycle seat as a bull's head or a cake as a hat)
** Eleven - Nuances: The Many Voices in the One
** Twelve - Yin-Yang: Polarity and Creative Tension
** Thirteen - Brevity and Re-Vision: Less is More
** Fourteen - Designing Constellations: Worlds Within Worlds
* Directing Your Hand
** Trial Webs From Pictures
1. Look at an image. When a dominant impression occurs to you, write it down as the nucleus of a cluster.
   - The nucleus can be anything: a title, a metaphor, a feeling, a description. If nothing jumps out ask "How does this make me feel?"
2. Cluster around the impression, continuing to look at the image, until a trial-web shift happens.
3. Write  for five minutes. Only use the things from your cluster that match the pattern that impelled you to write, bringing it full-circle at the end.
4. Read it out loud and change what you need to.
** Inverse Clustering (Bottoms-Up): Re-Creation
1. Listen to a piece (or read it) first just for enjoyment.
2. Re-listen, this time clustering around an empty nucleus any words or phrases that stand out.
3. As with images, study the cluster until a dominant impression comes up that you can use for the nucleus.
4. Use the cluster to write a vignette.
** The Rhythm of Unknown Writing
1. Take a piece of writing done in a language you don't understand.
2. Cluster and write your version of what you think it's saying based on the sounds and rhythms of the words.
** Images: Color
1. Cluster around the nucleus "Color" until one jumps out at you
2. Cluster around the color from step one. Go for quantity so you don't get stuck in the obvious.
3. Write a focusing statement or two.
4. Write for five minutes.
5. Come full circle and then revise what you need to.
6. Read it alound.
** Images: Object Work
Cluster around the nucleus "This Is" things you associate with an object.
** Images: Dreams
1. Cluster your dreams for a week - use images not concepts.
2. Look at your clusters and try to remember the dreams they represent - fill in any missing images you remember.
3. Write a dream in first-person real-time.
4. Come full circle to the dominant impression of the dream-cluster.
** Images: Art
1. Start with an image or artwork
2. Look at the art, trying not to actively think "about" it but just look.
3. When you get a dominant impression use it as the nucleus for a cluster.
4. Cluster around the nucleus until the trial-web shift occurs.
5. Dump a couple of focusing statements for the cluster.
6. Write.
** Metaphor: How Would I Paint...?
1. Use as your nucleus "How would I paint <thing>?"
2. Cluster all your senses - what do you see, hear, taste, etc.
** Metaphor: Personification
1. Use your abstract subject as the nucleus.
2. Cluster attributes of a person representing the nucleus.
** Nuances: Modeling Voice
1. Pick a passage that you want to use as a model.
2. Read it out loud.
3. Cluster around a word or phrase taken from the model until you experience the trial-web shift.
4. Write your subject while keeping the voice of the model in mind. Write until you can come full circle.
5. Read your piece out loud and make any adjustments.
** Nuances: Dialogue
1. Pre-Cluster pairs of names whose dialog you want to hear.
2. Once the impulse to write comes create two clusters, one for each end of the dialog and cluster ideas, feelings, snippets of dialogue, etc. for the two.
3. Write the impulse that emerged from the two clusters as a dialogue between them.
* Source
- [WTNW] Rico GL. Writing the natural way: using right-brain techniques to release your expressive powers. Rev. ed. New York: Tarcher/Putnam; 2000. 262 p. 

- ISBN: 976-0-87477-961-5
