#+BEGIN_COMMENT
.. title: They Say: Exercises
.. slug: they-say-exercises
.. date: 2020-09-05 18:17:45 UTC-07:00
.. tags: exercises,writing,rhetoric
.. category: Writing
.. link: 
.. description: Exercises for stating what others' opinions are.
.. type: text
.. status: 
.. updated: 

#+END_COMMENT
#+OPTIONS: ^:{}
#+TOC: headlines 2
* Add They Say
** Poisoned Water
#+begin_quote
Our experiments suggest that there are dangerous levels of chemical X in the Ohio groundwater.
#+end_quote

#+begin_quote
Many people assume that Ohio's water is safe and healthy to drink, but our experiments suggest that there are dangerous levels of chemical X in the Ohio groundwater.
#+end_quote
** Fabricated History
#+begin_quote
Material forces drive history.
#+end_quote

#+begin_quote
It is often said that our destiny is up to Fate, when really material forces drive history.
#+end_quote

** Rational Freud

#+begin_quote
Proponents of Freudian psychology question standard notions of "rationality".
#+end_quote

#+begin_quote
You would think that psychologists would agree on something as fundamental as what rationality is, but proponents of Freudian psychology question standard notions of "rationality".
#+end_quote

** Male Dominance
#+begin_quote
Male students often dominate class discussions.
#+end_quote

#+begin_quote
Common sense seems to dictate that the academic world would be a place where diversity of opinion and gender equity would be encouraged, but in reality male students often dominate class discussions.
#+end_quote

** Filmed Romance
#+begin_quote
The film is about the problems of romantic relationships.
#+end_quote

#+begin_quote
People often assume that /King Kong/ is a monster movie when actually the film is about the problems of romantic relationships.
#+end_quote
** Stifled Creativity
#+begin_quote
I'm afraid that templates like the ones in this book will stifle my creativity.
#+end_quote

#+begin_quote
Graff and Birkenstein state that using their templates will encourage originality but I'm afraid that templates like the ones in this book will stifle my creativity.
#+end_quote

* Zinczenko's Way

#+begin_quote
If ever there was an idea custom-made for a Jay Leno monologue, this was it: __. Isn't that like __? Whatever happened to __?

I happen to sympathize with __, though, perhaps because __.
#+end_quote
