#+BEGIN_COMMENT
.. title: 2D Static Noise (Setting the Pixel Array)
.. slug: 2d-static-noise-setting-the-pixels
.. date: 2023-07-16 13:57:32 UTC-07:00
.. tags: nature of code,p5.js,noise
.. category: Noise
.. link: 
.. description: Graphing p5.js noise using the pixel array.
.. type: text
.. status: 
.. updated: 
.. template: p5.tmpl
#+END_COMMENT
#+OPTIONS: ^:{}
#+TOC: headlines 2


{{% javascripttag source="pixel-constants.js" %}}
{{% javascripttag source="noise-plotter.js" %}}

This will essentially be the same sketch as in the {{% doc %}}2d-noise-using-set{{% /doc %}} post except instead of using the ~set~ function I'll set the values in the [[https://p5js.org/reference/#/p5/pixels][~pixels~]] array directly.

* Some Constants

I'm not as familiar with javascript as I am with python so I was littering constant values all over the place trying to figure where the best place to put them would be. I finally decided to create these two objects to hold some constants that I'll use when updating the pixels array and when setting the slider up.

#+begin_src js :tangle ../files/posts/2d-static-noise-setting-the-pixels/pixel-constants.js :exports none
/** Some constants to use when setting values in the pixels array */
<<pixel-constants-pixel-array>>

/** Constants to use when setting up the sliders */
<<pixel-constants-slider>>
#+end_src

#+begin_src js :noweb-ref pixel-constants-pixel-array
const PIXEL_ARRAY = {
  RED: 0,
  GREEN : 1,
  BLUE : 2,
  ALPHA : 3,
  CELLS_PER_PIXEL : 4,
  RGB_MAX : 255,
} // end PIXEL_ARRAY
#+end_src

The RED, GREEN, BLUE, and ALPHA values are to help locate their relative location in the array (more on that later), as is the CELLS_PER_PIXEL. I made RGB_MAX is so that maybe it's a little more obvious why there's a number 255 showing up in the code.

#+begin_src js :noweb-ref pixel-constants-slider
const SLIDER = {
  min: 0,
  max: 1,
  default_value: 0.01,
  step_size: 0,
} // end SLIDER_SETTINGS
#+end_src

These are the same values I used in the previous noise-sketches. A ~step_size~ of 0 just means that I'm not setting one so p5 can use whatever the default value is - the documentation says it's continuous but it seems to jump a bit when I use it.

* Noise Plotter

The Noise Plotter class is going to draw the two-dimensional noise-visualization using the current slider value as the step-size to change the noise input.

#+begin_src js :tangle ../files/posts/2d-static-noise-setting-the-pixels/noise-plotter.js :exports none
/** Plot Two-Dimensional Noise */
<<noise-plotter-class>>

  /** Construct the Noise Plotter
   ,* Params:
   ,*  - p5: p5 instance object
   ,*  - slider: slider to grab the noise-offset increment value
  ,*/
  <<noise-plotter-constructor>>

  <<noise-plotter-draw>>

    <<noise-plotter-draw-load-pixels>>
} // end NoisePlotter
#+end_src

*** The Noise Plotter Class
So, let's get started with the class definition.

#+begin_src js :noweb-ref noise-plotter-class
class NoisePlotter {
#+end_src

There's nothing really being done in the constructor except storing the p5 and slider objects for later.

#+begin_src js :noweb-ref noise-plotter-class
  constructor(p5, slider) {
    this.slider = slider;
    this.p5 = p5
  } // end constructur
#+end_src

*** The Draw Method
This is the workhorse that does all the plotting.

#+begin_src js :noweb-ref noise-plotter-draw
draw() {
  let intensity;
  let column_offset;
  let offset_increment = this.slider.value()
  let row_offset = 0;
  let pixel_index;
#+end_src

The variables:

- ~intensity~: This will hold the RGB value(s) that we set the pixels to based on noise
- ~column_offset~: The y-input for the noise function
- ~offset_increment~: How much to increase the noise function inputs (the offsets) in the loops
- ~row_offset~: x-input for the noise function
- ~pixel_index~: Starting index in the ~pixels~ array for our pixel

That last variable might take some explaining, so maybe here's a good spot to dump my understanding of how this works.

#+begin_src js :noweb-ref noise-plotter-draw-load-pixels
  this.p5.loadPixels();
  
  for (let y=0; y < this.p5.height; y++) {
    column_offset = 0;
    for (let x=0; x < this.p5.width; x++) {
      pixel_index = (x + y * this.p5.width) * PIXEL_ARRAY.CELLS_PER_PIXEL;
      intensity = this.p5.noise(column_offset, row_offset) * PIXEL_ARRAY.RGB_MAX;
      this.p5.pixels[pixel_index +
                     PIXEL_ARRAY.RED] = intensity;
      this.p5.pixels[pixel_index +
                     PIXEL_ARRAY.GREEN] = intensity;
      this.p5.pixels[pixel_index +
                     PIXEL_ARRAY.BLUE] = intensity;
      this.p5.pixels[pixel_index +
                     PIXEL_ARRAY.ALPHA] = PIXEL_ARRAY.RGB_MAX;
      column_offset += offset_increment;        
    } // end x for
    row_offset += offset_increment;
  }// end x for
  this.p5.updatePixels();
} // end draw
#+end_src
* The Sketch
*Note for later:* You have to either set the background or the set the alpha channel in the pixel array. Leaving both out won't show anything.


#+begin_src js :tangle ../files/posts/2d-static-noise-setting-the-pixels/static-sketch-pixels.js :exports none
const STATIC_NOISE_PIXELS_DIV = "static-2d-noise-graph-pixels";

/** Draw static 2D noise using pixel array
 ,* Params:
 ,* - p5: p5 instance object
 ,*/
<<static-pixels-function>>
  
  /** setup the canvas
   ,* - sets pixel density to 1 to make it easier to work with
   ,* - creates the canvas
   ,* - creates a slider with a callback to update if it's change
   ,* - sets up the text attributes to print the slider setting
   ,* - creates a NoisePlotter object to plot the noise
   ,* - Turns off the draw loop
  ,*/
  <<static-pixels-setup>>
    <<static-pixels-density>>

    <<static-pixels-canvas>>

    <<static-pixels-slider>>

    <<static-pixels-slider-callback>>

    <<static-pixels-slider-text-setup>>

    <<static-pixels-slider-noise-plotter>>

    <<static-pixels-slider-no-loop>>
  /** draw the noise */
  <<static-pixels-draw>>
} // end static_pixels

<<static-pixels-p5>>
#+end_src

*** The Closure Function

#+begin_src js :noweb-ref static-pixels-function
function static_pixels(p5) {
  const HEIGHT = 400;

  let plotter;
  let slider;
#+end_src

Once again, this is the sketch function that gets passed to a p5 constructor. I decided to create a class to handle the drawing of the visualization so the ~plotter~ variable is going to hold an instance of that. I'm also going to add a slider so that a user can change the amount the input to the noise changes, which is what the ~silder~ variable is for.

*** Set Up

#+begin_src js :noweb-ref static-pixels-setup
p5.setup = function() {
#+end_src

Just the basic p5 setup function.

**** You Are My Density

#+begin_src js :noweb-ref static-pixels-density
p5.pixelDensity(1);
#+end_src

To draw the noise I'm going to set the values in the ~pixels~ array directly but that's actually not so straightforward as you might think. When we refer to a pixel, there's two things to consider -  there's a /logical/ pixel, which is what we referred to using the ~set~ function, and what most people probably think of when working with p5 - it's the (x, y) coordinate you've come to know and love, but that pixel doesn't necessarily map one-to-one with the physical pixels in a display. Because of this, the size of the ~pixels~ array and the number of cells within the array dedicated to each pixel depends on the display.

The [[https://p5js.org/reference/#/p5/pixels][pixels]] documentation shows the proper way to set all the physical pixels, which requires you to check the [[https://p5js.org/reference/#/p5/pixelDensity][pixelDensity]] and then for each logical pixel you would loop over the sub-pixels that represent it... maybe some other time. For now, setting ~pixelDensity(1)~ will turn off matching the pixel density of the user's display and let us just worry about the one logical pixel. I don't know if that means it wont' take advantage of a higher density display or not, but p5 is about making it easier to code visualizations, not high performance (to me, anyway) - and as we'll see, the for-loops we're using are already slow enough, adding two more nested loops will just make things even slower.

**** The Canvas
#+begin_src js :noweb-ref static-pixels-canvas
p5.createCanvas(
  document.getElementById(STATIC_NOISE_PIXELS_DIV).offsetWidth,
  HEIGHT);
#+end_src

This is the usual code I use, nothing fancy.

**** The Slider
#+begin_src js :noweb-ref static-pixels-slider
slider = p5.createSlider(SLIDER.min,
                         SLIDER.max,
                         SLIDER.default_value,
                         SLIDER.step_size);
slider.style("width", "500px");
#+end_src

This is also a pretty straight-forward slider (although I think that just dropping it in after the canvas like this isn't what you're supposed to do). The main difference is that I'm adding a callback:

#+begin_src js :noweb-ref static-pixels-slider-callback
slider.input(() => p5.redraw());
#+end_src

This uses javascript's crazy [[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions][arrow function]] syntax (not that I think the idea behind it is crazy, but the weird looking syntax and the fact that there's so many ways to declare functions seems to make the language too complicated for the little advantage you get with all the variations).

Since this is a mostly static drawing I'm going to turn off re-drawing the canvas, but this callback tells p5 that if the user changes the slider's value then it should re-draw the canvas. p5 also has a similar function called ~changed~, but that doesn't trigger the callback until you let go of the mouse button, while ~input~ lets you see the changes as you drag the slider.

*Note:* [[https://p5js.org/reference/#/p5/input][input]] and [[https://p5js.org/reference/#/p5/changed][changed]] don't show up under the ~slider~ documentation but rather under the ~DOM~ category of the documentation so I don't know how anyone is supposed to know that they exist without searching forum posts. This seems to suggest that there might be other features of the p5 language that exist but aren't well documented so it's just luck if you figure out that they are there...

**** Text Setup
#+begin_src js :noweb-ref static-pixels-slider-text-setup
  p5.fill("white");
  p5.stroke("white");
  p5.textAlign(p5.CENTER);
  p5.textSize(32);
  p5.noStroke()
  #+end_src

  This sets the values that I'll use to show what the current slider value is to the user. Since I'm setting the pixel array values directly and not calling any functions like ~stroke~ or ~fill~ to do the visualization, setting it here will stick for the life of the sketch.

**** A Noise Plotter
#+begin_src js :noweb-ref static-pixels-slider-noise-plotter
plotter = new NoisePlotter(p5, slider);
#+end_src

I thought that it was getting cluttered up enough that it would make sense to break the plotting of the noise into a class, since I findi it easier to work with an object-oriented approach.

**** No Loop
#+begin_src js :noweb-ref static-pixels-slider-no-loop
  p5.noLoop();
} // end setup
#+end_src

The last thing in the setup is turning off the re-drawing of the canvas. I'm still not clear on what the difference is between putting it here and in the ~draw~ function. It seems to work the same in both cases.

*** Draw

Now, our draw function.

#+begin_src js :noweb-ref static-pixels-draw
  p5.draw = function() {
    plotter.draw();
    // add a label to show the amount the noise changes
    p5.text(`Noise Change: ${slider.value().toFixed(3)}`,
            p5.width/2 , p5.height - 10);
  } // end draw
#+end_src

Because I'm deferring most of the plotting to the ~NoisePlotter~ object it just calls its ~draw~ method and then sets the text to let the user know what the current slider setting is.

*** The P5 Instance

#+begin_src js :noweb-ref static-pixels-p5
new p5(static_pixels, STATIC_NOISE_PIXELS_DIV);
#+end_src

And then we create the p5 object...

* The Output

{{% p5div source="static-sketch-pixels.js" divid="static-2d-noise-graph-pixels" %}}

* Navigation Links

 - {{% lancelot title="Index Post for this Series" %}}two-dimensional-noise{{% /lancelot %}}
 - {{% lancelot title="Previously: Using the 'set' Method" %}}2d-noise-using-set{{% /lancelot %}}
 - {{% lancelot title="Next: Moving the Noise" %}}2d-moving-noise{{% /lancelot %}}
