* Emo Phillips
1. Once I was at a restaurant and I dropped my fork on the floor and they gave me a new fork. So I pushed my girlfriend out of her chair.
2. So, I'm at the wailing wall, standing there like a moron, with my harpoon.
3. I read than nine out of ten women fantasize about having an unknown man leap through their bedroom window at night and make mad, passionate love to them. Who would think that with those odds I would be facing one-hundred fifty hours of community service.
* Steven Wright
4. Some friends of mine got me a sweater for my birthday. I'd have preferred a moaner or a screamer, but the sweater was OK.
5. Is it true that cannibals don't eat clowns because they taste funny?
6. If toast always lands butter-side down and cats always land on their feet, what happens if you strap toast to the back of a cat and drop it?
7. Last night I played a blank tape at full blast. The mime next door went nuts.
8. The other night I was laying on my back looking up at the stars, and I wondered, "Where the hell is my roof?"
* Dmitri Martin
9. Sometimes if I want to get someone's attention I'll start a sentence with something like, "I'm not a racist but..." I say "I'm not a racist, but you look great today." They say "that wasn't racist at all." I said "I know. I said I'm not racist. Typical Mexican."
10. I was making pancakes the other day and a fly flew in the kitchen. And that's when I realized that a spatula is a lot like a fly swatter. And a crushed fly is a lot like a blueberry. And a roommate is a lot like a fly eater.
11. When people show me pictures of their kids it's okay, but when I give them a picture of me to show their kids I'm weird. What kind of one way street is that?
* Norm MacDonald
12. They say if you're afraid of homosexuals it means that deep down inside you're actually a homosexual yourself. That worries me because I'm afraid of dogs.
